name: "Unshiter"
author: "Thierry Crouzet"
author_url: "https://tcrouzet.com"
description: "Exploration statistique de textes littéraires et comparaison des corpus de divers auteurs."
copyright: "(cc) [Thierry Crouzet](https://tcrouzet.com) - (date) - {livres} œuvres - [Projet sur GitHub](https://github.com/tcrouzet/unshiter)"